font_size 8.0
background_opacity 0.7
foreground #cff4fb
background #060b26
cursor #9beaf2
cursor_text_color #070213

selection_foreground #070213
selection_background #94bdf2

url_color #9594f2

color8 #070213
color0 #060b26

color9 #f53c3c
color1 #f57a3c

color10 #00ed8d
color2 #5affb9

color3 #f2d974
color11 #ffb954

color12 #9594f2
color4 #94bdf2

color13 #aa52ec
color5 #bd94f2

color14 #55ddea
color6 #9beaf2

color15 #c2f5ff
color7 #cff4fb

