general {
	lock_cmd = pidof hyprlock || hyprlock
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'

}

$TIMEOUT = 60


listener {
	timeout = $TIMEOUT
	on-timeout = smooth-dim.sh
	on-resume = pkill smooth-dim.sh ; brightnessctl -r
}

listener {
	timeout = {{ $TIMEOUT + 10 }}
	on-timeout = loginctl lock-session && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
	on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
	timeout = 600
	on-timeout = systemctl suspend
}
